# Diese Datei konfiguriert den Analyzer, der Dart-Code statisch analysiert,
# um Fehler, Warnungen und Lints zu überprüfen.
#
# Die vom Analyzer erkannten Probleme werden in der UI von Dart-fähigen IDEs
# (https://dart.dev/tools#ides-and-editors) angezeigt. Der Analyzer kann auch
# über die Kommandozeile mit `flutter analyze` ausgeführt werden.

# Die folgende Zeile aktiviert eine empfohlene Menge an Lints für Flutter-Apps,
# Pakete und Plugins, die gute Programmierpraktiken fördern sollen.
include: package:flutter_lints/flutter.yaml

linter:
  # Die auf dieses Projekt angewendeten Lint-Regeln können im folgenden Abschnitt
  # angepasst werden, um Regeln aus `package:flutter_lints/flutter.yaml` zu deaktivieren
  # oder zusätzliche Regeln zu aktivieren. Eine Liste aller verfügbaren Lints und deren
  # Dokumentation ist unter https://dart.dev/lints veröffentlicht.
  #
  # Statt eine Lint-Regel für das gesamte Projekt zu deaktivieren, kann sie auch für
  # eine einzelne Codezeile oder eine bestimmte Dart-Datei mit der Syntax
  # `// ignore: name_of_lint` und `// ignore_for_file: name_of_lint` in der jeweiligen
  # Zeile oder Datei unterdrückt werden.
  rules:
    # Übersichtlichkeit & Lesbarkeit
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    always_put_control_body_on_new_line: true
    always_declare_return_types: true
    sort_pub_dependencies: true
    file_names: true
    # Kommentare & Dokumentation
    public_member_api_docs: false # Für öffentliche APIs ggf. auf true setzen
    # Flutter-spezifisch
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    avoid_returning_null_for_void: true
    avoid_print: true
    # Test-Konventionen
    avoid_redundant_argument_values: true
    # Naming
    camel_case_types: true
    library_prefixes: true
    # Import-Konventionen
    always_use_package_imports: false # Erlaube relative Imports
    prefer_relative_imports: true # Bevorzuge relative Imports im Projekt
    # Optional: weitere Regeln nach Team-Absprache

# Entfernte nicht unterstützte Lint-Regeln:
# lines_between_class_members
# lines_between_types

# Weitere Informationen zu dieser Datei finden Sie unter
# https://dart.dev/guides/language/analysis-options
